version: "3"

services:
  logtail:
    image: timberio/vector:latest-alpine
    volumes:
      - ./etc/vector.toml:/etc/vector/vector.toml:ro
      - /var/log:/var/log:ro
    environment:
      - LOGTAIL_TOKEN=${BETTER_STACK_TOKEN}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
