[workspace]
members = ["bin/searcher-reth","crates/extension","crates/core","crates/manager", "crates/config", "crates/strategy"]
resolver = "2"
[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
#searcher-reth
searcher-reth = { path = "bin/searcher-reth" }
searcher-reth-core = { path = "crates/core" }
searcher-reth-extension = { path = "crates/extension" }
searcher-reth-manager = { path = "crates/manager" }
searcher-reth-config = { path = "crates/config" }
searcher-reth-strategy = { path = "crates/strategy" }

# reth
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12", features = ["full"] }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-ethereum-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-discv5 = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-execution-errors = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12", features = ["serde"] }
reth-eth-wire = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-network = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12", features = ["test-utils"] }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }


# alloy
alloy-network = { version = "0.14", default-features = false }
alloy-eips = { version = "0.14", default-features = false }
alloy-genesis = { version = "0.14", default-features = false }
alloy-consensus = { version = "0.14", default-features = false }
alloy-rlp = "0.3.4"
alloy-rpc-types = { version = "0.14", features = [
    "eth",
], default-features = false }
alloy-signer = { version = "0.14", default-features = false }
alloy-signer-local = { version = "0.14", features=["mnemonic"] }

alloy-primitives = { version = "1.1", default-features = false }
alloy-sol-types  = { version = "1.1", features = ["json"] }

discv5 = "0.9"
enr = "0.13"
secp256k1 = { version = "0.30", default-features = false, features = [
 "global-context", "std", "recovery",
] }

# async
futures = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = ["full"] }

# serde
serde = "1"
serde_json = "1"

# misc
eyre = "0.6"

# testing
reth-exex-test-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }
reth-testing-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.12" }

#toml
toml = "0.8.22"

#clap
clap = "4.5.37"
rayon = "1.10.0"
