[package]
name = "searcher-reth-manager"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth-tracing.workspace = true
tokio.workspace = true
eyre.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true
alloy-network.workspace = true
alloy-signer-local.workspace = true
alloy-primitives.workspace = true
reth-revm.workspace = true
serde_json.workspace = true
