[package]
name = "searcher-reth-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
toml.workspace = true

eyre.workspace = true
alloy-network.workspace = true
alloy-signer-local.workspace = true
alloy-primitives.workspace = true

reth-revm.workspace = true
