[package]
name = "searcher-reth-repository"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true



[dependencies]
reth-revm.workspace = true
eyre.workspace = true
tokio.workspace = true

diesel = { workspace = true, features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }

dotenvy.workspace = true
searcher-reth-strategy.workspace = true
