[package]
name = "searcher-reth-repository"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true



[dependencies]
reth-revm.workspace = true
eyre.workspace = true
tokio.workspace = true

diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }

dotenvy = "0.15"