[package]
name = "searcher-reth-strategy"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true


[dependencies]
# reth
reth-chainspec.workspace = true
reth-evm.workspace = true
reth-execution-errors.workspace = true
reth-execution-types.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-tracing.workspace = true
reth.workspace = true

# alloy
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-eips.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-sol-types.workspace = true
alloy-network.workspace = true
alloy-signer-local.workspace = true
alloy-rpc-types.workspace = true

# async
futures-util.workspace = true
futures.workspace = true
tokio.workspace = true

# misc
eyre.workspace = true
rayon.workspace = true
reth-transaction-pool.workspace = true

#searcher-reth
searcher-reth-manager.workspace = true

#rocksdb
rocksdb.workspace = true

serde_json.workspace = true
reqwest.workspace = true
chrono.workspace = true
once_cell.workspace = true