[package]
name = "searcher-reth-relayer-pool"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
# reth
reth-evm.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-tracing.workspace = true
reth.workspace = true

# alloy
alloy-primitives.workspace = true

# async
futures-util.workspace = true
tokio.workspace = true

# misc
eyre.workspace = true
alloy-provider = { version = "1.0.5", features = ["ipc"] }
alloy = "1.0.6"
serde.workspace = true
toml = "0.8.22"
clap = "4.5.38"
tracing-subscriber = "0.3.19"
tracing-appender = "0.2.3"
searcher-reth-logger.workspace = true
searcher-reth-config = { version = "0.1.0", path = "../../crates/config" }
