[sources.searcher_logs]
 type = "file"
 include = ["/var/log/searcher-reth/*.log", "/var/log/searcher-tx-relayer/*.log"]

[transforms.parse_json]
 type = "remap"
 inputs = ["searcher_logs"]
 source = "\n  . = parse_json!(.message)\n"

[sinks.logtail]
 type = "http"
 inputs = ["parse_json"]
 uri = "https://in.logs.betterstack.com/"
 auth.strategy = "bearer"
 auth.token = "${LOGTAIL_TOKEN}"
 encoding.codec = "json"
 compression = "gzip"

