[package]
name = "searcher-reth-extension"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-evm.workspace = true
reth-execution-errors.workspace = true
reth-execution-types.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-tracing.workspace = true
reth.workspace = true

# alloy
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-eips.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-sol-types.workspace = true
alloy-network.workspace = true
alloy-signer-local.workspace = true
alloy-rpc-types.workspace = true

# async
futures-util.workspace = true
tokio.workspace = true

# misc
eyre.workspace = true

clap.workspace = true

searcher-reth-strategy.workspace = true
searcher-reth-manager.workspace = true
searcher-reth-indexer.workspace = true 

rayon.workspace = true
reth-transaction-pool.workspace = true

# postgres 
#tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4"] }